workflows:
  android-workflow:
    name: Android Build
    environment:
      flutter: stable
    scripts:
      - name: Clean and build
        script: |
          flutter clean
          flutter pub get
          flutter build appbundle --release
    artifacts:
      - build/app/outputs/bundle/**/*.aab
