name: shubh_kriski_kendra
description: "A new Flutter project for Shubh Krishi Kendra."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  
  # यहाँ हमने फ़्लटर के नए वर्शन्स के लिए इसे अपडेट कर दिया है
  file_picker: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # आपके एसेट्स फोल्डर का बिल्कुल सही रास्ता
  assets:
    - assets/images/
    - assets/data/
