name: shubh_kriski_kendra
description: "A new Flutter project for Shubh Krishi Kendra."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  
  # यहाँ हमने 8.0.1 कर दिया है ताकि कोडेमैजिक जबरदस्ती नया पैकेज डाउनलोड करे
  file_picker: 8.0.1
  provider: ^6.1.2
  image_picker: ^1.0.7
  share_plus: ^7.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/data/
