workflows:
  android-workflow:
    name: Android Build
    environment:
      flutter: stable
      gradle: 8.7
    scripts:
      - name: Clean and build
        script: |
          flutter clean
          flutter pub get
          cd android
          chmod +x gradlew
          ./gradlew wrapper --gradle-version=8.7
          cd ..
          flutter build appbundle --release
    artifacts:
      - build/app/outputs/bundle/**/*.aab
